accounts/urls.py
from django.urls import path
from .views import login_view, logout_view  # Import your custom view

app_name = "accounts"
urlpatterns = [
    path('accounts/login/', login_view, name="login"),
    path('accounts/logout/', logout_view, name="logout"),  # Use your custom view
]

jahdai/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]

students/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('<int:id>', views.view_student, name='view_student'),
	path('add/', views.add, name='add'),
	path('edit/<int:id>/', views.edit, name='edit'),
	path('delete/<int:id>/', views.delete, name='delete'),
	# Staff urls
	path('staff/', views.staff, name='staff'),
	path('<int:id>/',  views.view_staff, name='view-staff'),
	path('add_staff/', views.add_staff, name='add-staff'),
	path('edit_staff/<int:id>/', views.edit_staff, name='edit-staff'),
	path('delete_staff/<int:id>/', views.delete_staff, name='delete-staff'),
	path('notify_incident/<int:student_id>/', views.notify_incident, name='notify_incident'),

]

students/models.py
from django.db import models

class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    mother_Fname = models.CharField(max_length=50)
    mother_Lname = models.CharField(max_length=50)
    father_Fname = models.CharField(max_length=50)
    father_Lname = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    fee = models.FloatField()

    FEE_STATUS_CHOICES = [
        ('paid', 'Paid'),
        ('due', 'Due'),
        ('past', 'Past Due'),
    ]

    fee_status = models.CharField(max_length=10, choices=FEE_STATUS_CHOICES)

    STUDENT_STATUS_CHOICES = [
        ('current', 'Current Student'),
        ('past', 'Past Student'),
        ('sick', 'Sick Student'),
    ]

    student_status = models.CharField(max_length=10, choices=STUDENT_STATUS_CHOICES)
    allergies = models.CharField(max_length=255)

    def __str__(self):
        return f'Student: {self.first_name} {self.last_name}'


class Certification(models.Model):
    CERT_CHOICES = [
        ('first_aid', 'First Aid'),
        ('cpr', 'CPR'),
        ('6m_criminal_record', '6m Criminal Record'),
        ('1yr_criminal_record', '1yr Criminal Record'),
    ]

    name = models.CharField(max_length=50, choices=CERT_CHOICES)

    def __str__(self):
        return self.get_name_display()



class Staff(models.Model):
    staff_first_name = models.CharField(max_length=50)
    staff_last_name = models.CharField(max_length=50)
    staff_birth_date = models.DateField()
    staff_email = models.EmailField()
    staff_phone = models.CharField(max_length=15)
    

    CERTIFICATE_CHOICES = [
        ('first_aid', 'First Aid'),
        ('cpr', 'CPR'),
        ('6m_criminal_record', '6m Criminal Record'),
        ('1yr_criminal_record', '1yr Criminal Record'),
    ]
    certificates = models.ManyToManyField(Certification, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

students/forms.py
from django import forms
from .models import Student, Staff, Certification

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name', 'last_name', 'birth_date', 'mother_Fname', 'mother_Lname',
            'father_Fname', 'father_Lname', 'email', 'phone', 'fee', 'fee_status',
            'student_status', 'allergies'
        ]
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'birth_date': 'Birth Date',
            'mother_Fname': "Mother's First Name",
            'mother_Lname': "Mother's Last Name",
            'father_Fname': "Father's First Name",
            'father_Lname': "Father's Last Name",
            'email': 'Email',
            'phone': 'Phone',
            'fee': 'Fee',
            'fee_status': 'Fee Status',
            'student_status': 'Student Status',
            'allergies': 'Allergies'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'mother_Fname': forms.TextInput(attrs={'class': 'form-control'}),
            'mother_Lname': forms.TextInput(attrs={'class': 'form-control'}),
            'father_Fname': forms.TextInput(attrs={'class': 'form-control'}),
            'father_Lname': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'fee': forms.NumberInput(attrs={'class': 'form-control'}),
            'fee_status': forms.Select(attrs={'class': 'form-control'}, choices=Student.FEE_STATUS_CHOICES),
            'student_status': forms.Select(attrs={'class': 'form-control'}, choices=Student.STUDENT_STATUS_CHOICES),
            'allergies': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CertForm(forms.ModelForm):
    class Meta:
        model = Certification
        fields = ['name']
        widgets = {
            'name': forms.CheckboxSelectMultiple,
        }




class StaffForm(forms.ModelForm):
    certificates = forms.ModelMultipleChoiceField(
        queryset=Certification.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta:
        model = Staff
        fields = [
            'staff_first_name', 'staff_last_name', 'staff_birth_date', 'staff_email', 
            'staff_phone', 'certificates'
        ]
        labels = {
            'staff_first_name': 'First Name',
            'staff_last_name': 'Last Name',
            'staff_birth_date': 'Birth Date',
            'staff_email': 'Email',
            'staff_phone': 'Phone',
            'certificates': 'Certification'
        }
        widgets = {
                'staff_first_name': forms.TextInput(attrs={'class': 'form-control'}),
                'staff_last_name': forms.TextInput(attrs={'class': 'form-control'}),
                'staff_birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
                'staff_email': forms.EmailInput(attrs={'class': 'form-control'}),
                'staff_phone': forms.TextInput(attrs={'class': 'form-control'}),
        }   



class IncidentForm(forms.Form):
    incident_report = forms.CharField(widget=forms.Textarea)

students/views.py
from django.shortcuts import render, redirect
from .models import Student, Staff, Certification
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail
from .forms import StudentForm, StaffForm, IncidentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url="/accounts/login/")
def index(request):
	return render(request, 'students/index.html', {
		'students':Student.objects.all()
	})



@login_required(login_url="/accounts/login/")
def view_student(request, id):
	student = Student.objects.get(pk=id)
	return HttpResponseRedirect(reverse('index'))




@login_required(login_url="/accounts/login/")
def add(request):
	if request.method == 'POST':
		form = StudentForm(request.POST)
		if form.is_valid():
			new_first_name = form.cleaned_data['first_name']
			new_last_name = form.cleaned_data['last_name']
			new_birth_date = form.cleaned_data['birth_date']
			new_mother_Fname = form.cleaned_data['mother_Fname']
			new_mother_Lname = form.cleaned_data['mother_Lname']
			new_father_Fname = form.cleaned_data['father_Fname']
			new_father_Lname = form.cleaned_data['father_Lname']
			new_email = form.cleaned_data['email']
			new_phone = form.cleaned_data['phone']
			new_fee = form.cleaned_data['fee']
			new_fee_status = form.cleaned_data['fee_status']
			new_student_status = form.cleaned_data['student_status']
			new_allergies = form.cleaned_data['allergies']

			new_student = Student(
				first_name = new_first_name,
				last_name = new_last_name,
				birth_date = new_birth_date,
				mother_Fname = new_mother_Fname,
				mother_Lname = new_mother_Lname,
				father_Fname = new_father_Fname,
				father_Lname = new_father_Lname	,
				email = new_email,
				phone = new_phone,
				fee = new_fee,
				fee_status = new_fee_status,
				student_status = new_student_status,
				allergies = new_allergies,
			)
			new_student.save()
			return render(request, 'students/add.html', {
				'form': StudentForm(),
				'success': True
			})
	else:
		form = StudentForm()
	return render(request, 'students/add.html', {
		'form': StudentForm()
		})



@login_required(login_url="/accounts/login/")
def edit(request, id):
    if request.method == 'POST':
        student = Student.objects.get(pk=id)
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return render(request, 'students/edit.html', {
                'form': form,
                'success': True
            })
    else:
        student = Student.objects.get(pk=id)
        form = StudentForm(instance=student)
    return render(request, 'students/edit.html', {
        'form': form
    })




@login_required(login_url="/accounts/login/")
def delete(request, id):
	if request.method == "POST":
		student = Student.objects.get(pk=id)
		student.delete()
	return HttpResponseRedirect(reverse('index'))



def staff(request):
	return render(request, 'students/staff.html', {
		'staff':Staff.objects.all()
	})



def view_staff(request, id):
	staff = Staff.objects.get(pk=id)
	return HttpResponseRedirect(reverse('index'))



def edit_staff(request, id):
    if request.method == 'POST':
        staff_members = Student.objects.get(pk=id)
        form = StaffForm(request.POST, instance=staff_members)
        if form.is_valid():
            form.save()
            return render(request, 'students/edit_staff.html', {
                'form': form,
                'success': True
            })
    else:
        staff_members = Staff.objects.get(pk=id)
        form = StaffForm(instance=staff_members)
    return render(request, 'students/edit_staff.html', {
        'form': form
    })



def delete_staff(request, id):
	if request.method == "POST":
		staff_members = Staff.objects.get(pk=id)
		staff_members.delete()
	return HttpResponseRedirect(reverse('index'))


def add_staff(request):
	if request.method == 'POST':
		form = StaffForm(request.POST)
		if form.is_valid():
			new_staff_first_name = form.cleaned_data['staff_first_name']
			new_staff_last_name = form.cleaned_data['staff_last_name']
			new_staff_birth_date = form.cleaned_data['staff_birth_date']
			new_staff_email = form.cleaned_data['staff_email']
			new_staff_phone = form.cleaned_data['staff_phone']
			new_certificates = form.cleaned_data['certificates']
			

			new_staff = Staff(
				staff_first_name = new_staff_first_name,
				staff_last_name = new_staff_last_name,
				staff_birth_date = new_staff_birth_date,
				staff_email = new_staff_email,
				staff_phone = new_staff_phone,
				certificates = new_certificates,
				
			)
			new_staff.save()
			return render(request, 'students/add_staff.html', {
				'form': StaffForm(),
				'success': True
			})
	else:
		form = StaffForm()
	return render(request, 'students/add_staff.html', {
		'form': StaffForm()
		})




@login_required(login_url="/accounts/login/")
@csrf_exempt
def notify_incident(request, student_id):
    student = Student.objects.get(id=student_id)
    if request.method == 'POST':
        incident_report = request.POST.get('message')
        # Prepare the letter
        letter = f"""
        Dear Mr./Mrs/Ms. {student.last_name}:

        This serves as notice that your child, {student.first_name} {student.last_name},

        {incident_report}

        Please feel free to contact the school for any question(s), that you may have regarding this notice.

        Yours truly;
        """
        send_mail(
            'Incident Report',
            letter,
            'jahdaiscare@gmail.com',
            [student.email],
        )
        return redirect('index')  # Redirect to index after sending the email
    return render(request, 'students/notify_incident.html', {'student': student})

students/templates/students/add.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">ADD STUDENT</h3>
	{% if success %}
		<div class="alert-success" role="alert">
			{{ new_student.first_name }} {{ new_student.last_name }} has been added successfully.
			<a href="{% url 'index' %}" class='alert-link'>Go To Home Page</a>
		</div>
	{% else %}
		<div class='row jusify-content-center'>
			<div class='col-6'>
				<div class="card bg-light mb-3">
				  <div class="card-header">
				  	<i class="fa-solid fa-address-card fa-lg">&nbsp;Student Registration</i>
				  </div>
				  <div class="card-body">
				    <form action="{% url 'add' %}" method='POST'>
				    	{% csrf_token %}
				    	{{ form.as_p }}	    	
				    	<button type="submit" class="btn btn-primary">Add</button>
				    	<a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
				    </form>
				  </div>
				</div>
			</div>
	{% endif %}
{% endblock %}

students/templates/students/add_staff.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">ADD STAFF MEMBER</h3>
	{% if success %}
		<div class="alert-success" role="alert">
			{{ new_staff.staff_first_name }} {{ new_staff.staff_last_name }} has been added successfully.
			<a href="{% url 'index' %}" class='alert-link'>Go To Home Page</a>
		</div>
	{% else %}
		<div class='row jusify-content-center'>
			<div class='col-6'>
				<div class="card bg-light mb-3">
				  <div class="card-header">
				  	<i class="fa-solid fa-address-card fa-lg"> Staff Registration</i>
				  </div>
				  <div class="card-body">
				    <form action="{% url 'add' %}" method='POST'>
				    	{% csrf_token %}
				    	{{ form.as_p }}	    	
				    	<button type="submit" class="btn btn-primary">Add</button>
				    	<a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
				    </form>
				  </div>
				</div>
			</div>
        </div> <!-- This closing div tag was missing -->
    {% endif %}
{% endblock %}

students/templates/students/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Jahdai's Care SMS</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
</head>
	<body class="d-flex flex-column min-vh-100">
		<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <i class="fa-solid fa-graduation-cap fa-lg"></i>&nbsp;Student Management System
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">
                            <i class="fa-solid fa-list fa-lg"></i>&nbsp;All Students
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add' %}">
                            <i class="fa-solid fa-user-plus fa-lg"></i>&nbsp;Add Students
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'staff' %}">
                            <i class="fa-solid fa-person-chalkboard fa-lg"></i>&nbsp;All Staff
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add-staff' %}">
                            <i class="fa-solid fa-user-plus fa-lg"></i>&nbsp;Add Staff
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                            <i class="fa-solid fa-right-from-bracket"></i>&nbsp;Logout
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
	{% block body %}
	{% endblock %}

			</div>	
			<footer class="mt-auto mb-4">
				<div class="text-center">
											
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	</body>
</html>

students/templates/students/edit.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">EDIT STUDENT</h3>
	{% if success %}
		<div class="alert-success" role="alert">
			{{ student.first_name }} {{ student.last_name }} has been successfully updated.
			<a href="{% url 'index' %}" class='alert-link'>Go To Home Page</a>
		</div>
	{% else %}
		<div class='row jusify-content-center'>
			<div class='col-6'>
				<div class="card bg-light mb-3">
				  <div class="card-header">
				  	
				  </div>
				  <div class="card-body">
				    <form action="" method='POST'>
				    	{% csrf_token %}
				    	{{ form.as_p }}	    	
				    	<button type="submit" class="btn btn-primary">Save</button>
				    	<a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
				    </form>
				  </div>
				</div>
			</div>
	{% endif %}
{% endblock %}

students/templates/students/edit_staff.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">EDIT STAFF MEMBER</h3>
	{% if success %}
		<div class="alert-success" role="alert">
			{{ staff.staff_first_name }} {{ staff.staff_last_name }} has been successfully updated.
			<a href="{% url 'index' %}" class='alert-link'>Go To Home Page</a>
		</div>
	{% else %}
		<div class='row jusify-content-center'>
			<div class='col-6'>
				<div class="card bg-light mb-3">
				  <div class="card-header">
				  	
				  </div>
				  <div class="card-body">
				    <form action="" method='POST'>
				    	{% csrf_token %}
				    	{{ form.as_p }}	    	
				    	<button type="submit" class="btn btn-primary">Save</button>
				    	<a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
				    </form>
				  </div>
				</div>
			</div>
	{% endif %}
{% endblock %}

students/templates/students/incident_report_sent.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">Incident Report Sent</h3>
    <div class='row justify-content-center'>
        <div class='col-6'>
            <div class="card bg-light mb-3">
                <div class="card-header">
                    <!-- You can add a header here if you want -->
                </div>
                <div class="card-body">
                    <p>The incident report has been sent successfully.</p>
                    <a href="{% url 'index' %}" class="btn btn-primary">Back to Home</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

students/templates/students/index.html
{% extends "students/base.html" %}

{% block body %}
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    	<i class="fa-solid fa-graduation-cap fa-lg">&nbsp;</i>Student Management System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">
          	<i class="fa-solid fa-list fa-lg"></i>All Students</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
          	<i class="fa-solid fa-user-plus fa-lg"></i>Add Students</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
          	<i class="fa-solid fa-person-chalkboard fa-lg"></i>All Staff</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
          	<i class="fa-solid fa-user-plus fa-lg"></i>Add Staff</a>
        </li>
    </div>
  </div>
</nav>
	<div class="container-fluid">
		<h3 class="m-4">All Students</h3>
			<div class="row">
				<div class="col-12">
					{% if students %}
					<div class="card bg-light ms-4 me-4 mb-4">
					  <div class="card-header"><i class="fa-solid fa-list fa-lg"></i> Student Records</div>
					  <div class="card-body">
					    <p class="card-text">
					    	<div class="table-responsive">
					    		<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Student ID:</th>
      <th scope="col">Student Name:</th>
      <th scope="col">Birth Date:</th>
      <th scope="col">Fee Status:</th>
      <th scope="col">Student Status:</th>
      <th scope="col">Actions:</th>
    </tr>
  </thead>
  <tbody>
    {% for student in students %}
    <tr>
        <td>{{ student.id }}</td>
        <td>{{ student.first_name }} {{ student.last_name }}</td>
        <td>{{ student.birth_date }}</td>
        <td class="{% if student.fee_status == 'Paid' %}bg-success{% elif student.fee_status == 'Due' %}bg-warning{% elif student.fee_status == 'Past Due' %}bg-danger{% endif %}">{{ student.get_fee_status_display }}</td>


        <td class="{% if student.student_status == 'Current' %}bg-success{% elif student.student_status == 'Sick' %}bg-warning{% elif student.student_status == 'Past' %}bg-danger{% endif %}">
    {{ student.get_student_status_display }}
</td>

    	<td> <button type="button" class="btn btn-success me-1" href="{% url 'view_student' student.id %}" data-bs-toggle="modal" data-bs-target="#myModal{{student.id}}"><i class="fa-solid fa-circle-info fa-lg"></i></button>

    		<!-- Modal View Student -->
    		<div class="modal" id="myModal{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Student: {{ student.first_name }} {{ student.last_name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-unstyled">
        	<li> Student ID: <strong>{{ student.id }}</strong></li>
        	<li> Birth Date: <strong>{{ student.birth_date }}</strong></li>
		    	<li> Mother's Name: <strong>{{ student.mother_Fname }} {{ student.mother_Lname }}</strong></li>
		    	<li> Father's Name: <strong>{{ student.father_Fname }} {{ student.father_Lname }}</strong></li>
		    	<li> Email: <strong>{{ student.email }}</strong></li>
		    	<li> Phone: <strong>{{ student.phone }}</strong></li>
		    	<li> Fee: <strong>{{ student.fee }}</strong></li>
		    	<li> Fee Status: <strong>{{ student.fee_status }}</strong></li>
		    	 {% if student.student_status == 'Current' %}blue
            {% elif student.student_status == 'Sick' %}orange
            {% elif student.student_status == 'Past' %}red
            {% endif %}">
          <li> Student Status: <strong>{{ student.student_status }}</strong></li>
		    	<li> Allergies: <strong>{{ student.allergies }}</strong></li>
		    </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

  <a class="btn btn-warning me-1" href="{% url 'edit' student.id %}"><i class="fa-solid fa-pen-to-square fa-lg"></i></a>
  <a class="btn btn-danger me-1" href="{% url 'notify_incident' student.id%}"><i class="fa-regular fa-bell fa-lg"></i></a>
  <button type="button" class='btn btn-danger' data-bs-toggle="modal" data-bs-target="#delete{{student.id}}"><i class="fa-regular fa-trash-can fa-lg"></i>&nbsp;</button>

  <!--Modal - Delete Student -->
  <div class="modal" id="delete{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Student: {{ student.first_name }} {{ student.last_name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are You Sure You Want To Delete {{ student.first_name }} {{ student.last_name }}</p>
        
      </div>
      <div class="modal-footer">
        <form action="{% url 'delete' student.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Delete">
        </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

    	</td>

    {% endfor %}
  </tbody>
</table>

					    </p>
					  </div>
					</div>
					{% else %}
						<h5 class="alert-primary ms-4 me-4">No Records Found</h5>
					{% endif %}
					
				</div>
			</div>	
			<footer class="mt-auto mb-4">
				<div class="text-center">
					<span>
						Copyright &copy; <script>document.write(new Date().getFullYear())</script> Jahdai's Care Babysitting Services.
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	</body>
</html>


{% endblock %}

students/templates/students/notify_incident.html
{% extends 'students/base.html' %}

{% block body %}
<h3 class="text-center m-4">Send Incident Report</h3>
    <div class='row justify-content-center'>
        <div class='col-6'>
            <div class="card bg-light mb-3">
                <div class="card-header">
                    <!-- You can add a header here if you want -->
                </div>
                <div class="card-body">
                    <p>Dear Mr./Mrs/Ms. {{ student.last_name }}:</p>

                    <p>This serves as notice that your child, <em>{{ student.first_name }} {{ student.last_name }}</em>,</p>

                    <textarea id="message" name="message" rows="4" cols="50" placeholder="Type your message here..."></textarea>

                    <p>Please feel free to contact the school for any question(s), that you may have regarding this notice.</p>

                    <p>Yours truly;</p>
                    
                    <button id="sendButton" type="button" class="btn btn-primary">Send</button>
                    <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Your JavaScript code -->
    <script>
var notifyIncidentUrl = "{% url 'notify_incident' student.id %}";

$(document).ready(function() {
    $('#sendButton').click(function(e) {
        e.preventDefault();
        $.ajax({
            url: notifyIncidentUrl,
            type: 'post',
            data: {
                message: $('#message').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function() {
                window.location.href = "{% url 'index' %}";
            }
        });
    });
});
</script>

{% endblock %}